//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFISCAL_WEB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFISCAL_WEB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma a exclusão deste item?.
        /// </summary>
        internal static string MSG_A001 {
            get {
                return ResourceManager.GetString("MSG_A001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma saída sem gravação dos dados?.
        /// </summary>
        internal static string MSG_A002 {
            get {
                return ResourceManager.GetString("MSG_A002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja enviar sugestão para a ANTT?.
        /// </summary>
        internal static string MSG_A003 {
            get {
                return ResourceManager.GetString("MSG_A003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório..
        /// </summary>
        internal static string MSG_E001 {
            get {
                return ResourceManager.GetString("MSG_E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário e/ou senha inválidos – acesso não permitido..
        /// </summary>
        internal static string MSG_E002 {
            get {
                return ResourceManager.GetString("MSG_E002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro encontrado..
        /// </summary>
        internal static string MSG_E003 {
            get {
                return ResourceManager.GetString("MSG_E003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusão não permitida, dados vinculados a este item..
        /// </summary>
        internal static string MSG_E004 {
            get {
                return ResourceManager.GetString("MSG_E004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de arquivo não permitido!.
        /// </summary>
        internal static string MSG_E005 {
            get {
                return ResourceManager.GetString("MSG_E005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você está off-line, e este recurso requer acesso à internet..
        /// </summary>
        internal static string MSG_E006 {
            get {
                return ResourceManager.GetString("MSG_E006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível o acesso à rede da ANTT. Favor tentar mais tarde..
        /// </summary>
        internal static string MSG_E007 {
            get {
                return ResourceManager.GetString("MSG_E007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicativo não encontrado..
        /// </summary>
        internal static string MSG_E008 {
            get {
                return ResourceManager.GetString("MSG_E008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato da Ouvidoria não disponível. Favor escolher a opção “Formulário”..
        /// </summary>
        internal static string MSG_E009 {
            get {
                return ResourceManager.GetString("MSG_E009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número informado é inválido..
        /// </summary>
        internal static string MSG_E010 {
            get {
                return ResourceManager.GetString("MSG_E010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível inserir arquivo com tamanho superior a {0}..
        /// </summary>
        internal static string MSG_E011 {
            get {
                return ResourceManager.GetString("MSG_E011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data início deve ser menor que a data fim..
        /// </summary>
        internal static string MSG_E012 {
            get {
                return ResourceManager.GetString("MSG_E012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível inserir novo arquivo com a opção Offline. Para inserir novos arquivos deste tipo, é necessário excluir antigos e garantir o tamanho máximo previsto para o APP..
        /// </summary>
        internal static string MSG_E013 {
            get {
                return ResourceManager.GetString("MSG_E013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados gravados com sucesso!.
        /// </summary>
        internal static string MSG_S001 {
            get {
                return ResourceManager.GetString("MSG_S001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item excluído com sucesso!.
        /// </summary>
        internal static string MSG_S002 {
            get {
                return ResourceManager.GetString("MSG_S002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliação enviada!.
        /// </summary>
        internal static string MSG_S003 {
            get {
                return ResourceManager.GetString("MSG_S003", resourceCulture);
            }
        }
    }
}
